In [ ]:
import pandas as pd
import numpy as np

In [ ]:
merged_data=pd.read_csv("merged_data_some_visit.csv")

In [ ]:
merged_data

,PATNO,"('NP1COG', 'BL')","('NP1COG', 'V02')","('NP1COG', 'V04')","('NP1COG', 'V06')","('NP1COG', 'V08')","('NP1COG', 'V10')","('NP1COG', 'V12')","('NP1HALL', 'BL')","('NP1HALL', 'V02')",...,"('SDMTOTAL', 'V08')","('SDMTOTAL', 'V10')","('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
0,3000,0.25,0.125,0.00,0.25,0.25,0.00,0.25,0.0,0.0,...,0.519608,0.500000,0.519608,1.000000,1.000000,0.933333,0.866667,0.933333,1.000000,HC
1,3001,0.00,0.000,0.25,0.00,0.00,0.00,0.25,0.0,0.0,...,0.470588,0.470588,0.441176,1.000000,0.800000,1.000000,0.866667,0.933333,1.000000,PD
2,3002,0.25,0.250,0.25,0.50,0.25,0.25,0.50,0.0,0.0,...,0.431373,0.421569,0.372549,0.866667,0.800000,0.866667,0.733333,1.000000,0.866667,PD
3,3003,0.00,0.000,0.00,0.00,0.00,0.00,0.25,0.0,0.0,...,0.480392,0.411765,0.421569,0.866667,0.866667,0.933333,0.866667,1.000000,0.800000,PD
4,3004,0.00,0.000,0.00,0.00,0.25,0.00,0.00,0.0,0.0,...,0.450980,0.519608,0.500000,0.866667,0.866667,1.000000,0.933333,1.000000,1.000000,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,60059,0.25,0.250,0.00,0.00,0.00,0.00,0.00,0.0,0.0,...,0.156863,0.156863,0.156863,0.533333,0.533333,0.400000,0.733333,0.733333,0.533333,PRODROMA
472,60060,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.0,0.0,...,0.313725,0.254902,0.264706,0.800000,0.733333,0.733333,0.866667,0.866667,0.866667,PRODROMA
473,60063,0.00,0.000,0.00,0.00,0.00,0.25,0.25,0.0,0.0,...,0.156863,0.107843,0.117647,0.600000,0.600000,0.533333,0.533333,0.800000,0.400000,PRODROMA
474,65002,0.25,0.250,0.00,0.25,0.25,0.25,0.25,0.0,0.0,...,0.362745,0.421569,0.480392,0.800000,0.800000,0.733333,0.711111,0.688889,0.666667,GENUN
475,90456,0.25,0.250,0.25,0.50,0.25,0.25,0.25,0.0,0.0,...,0.215686,0.205882,0.215686,0.600000,0.533333,0.666667,0.466667,0.533333,0.466667,PRODROMA

In [ ]:
new_df=merged_data.loc[merged_data['ENROLL_CAT']=='PD']

In [ ]:
new_df2=merged_data.loc[merged_data['ENROLL_CAT']=='HC']

In [ ]:
new_df.to_csv('PPMI_PD.csv',index=None)
new_df2.to_csv('PPMI_HC.csv',index=None)

In [ ]:
frames = [new_df, new_df2]
result=pd.concat(frames)

In [ ]:
result

,PATNO,"('NP1COG', 'BL')","('NP1COG', 'V01')","('NP1COG', 'V02')","('NP1COG', 'V03')","('NP1COG', 'V04')","('NP1COG', 'V05')","('NP1COG', 'V06')","('NP1COG', 'V07')","('NP1COG', 'V08')",...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
1,3001,0.00,0.00,0.00,0.00,0.25,0.00,0.0,0.00,0.00,...,0.441176,1.000000,0.933333,0.866667,0.800000,1.000000,0.866667,0.933333,1.000000,PD
2,3002,0.25,0.25,0.25,0.25,0.25,0.25,0.5,0.25,0.25,...,0.372549,0.866667,0.844444,0.822222,0.800000,0.866667,0.733333,1.000000,0.866667,PD
3,3003,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.25,0.00,...,0.421569,0.866667,0.866667,0.866667,0.866667,0.933333,0.866667,1.000000,0.800000,PD
6,3010,0.25,0.00,0.25,0.00,0.00,0.25,0.0,0.00,0.25,...,0.539216,0.666667,0.733333,0.800000,0.866667,0.866667,0.866667,0.800000,0.933333,PD
7,3027,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.372549,0.866667,0.800000,0.733333,0.666667,0.833333,1.000000,0.833333,0.666667,PD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,4090,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.421569,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.933333,0.933333,HC
434,4100,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.441176,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,HC
437,4104,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.382353,0.800000,0.822222,0.844444,0.866667,0.933333,0.666667,0.733333,0.866667,HC
447,4116,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.421569,0.866667,0.911111,0.955556,1.000000,0.733333,0.933333,0.733333,0.933333,HC
449,4118,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.372549,0.800000,0.777778,0.755556,0.733333,0.866667,0.800000,0.933333,0.733333,HC

In [ ]:
result['ENROLL_CAT'] = result['ENROLL_CAT'].replace('HC',0)
result['ENROLL_CAT'] = result['ENROLL_CAT'].replace('PD',1)
result['ENROLL_CAT'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
trans_data=pd.read_csv('trans_data.csv')

In [ ]:
trans_data

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,Total_Force_Left_skew,Total_Force_Left_kurt,Total_Force_Right_min,Total_Force_Right_max,Total_Force_Right_mean,Total_Force_Right_median,Total_Force_Right_std_dv,Total_Force_Right_skew,Total_Force_Right_kurt,Label
0,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,-0.021240,-1.813475,0.0,773.85,326.325488,455.510,288.823810,-0.061878,-1.788584,0
1,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,-0.019703,-1.774458,0.0,1129.26,469.552123,597.410,404.868046,-0.047013,-1.725542,1
2,0.0,295.13,60.031170,5.06,82.694408,1.058844,-0.369829,0.0,469.15,98.999946,...,0.030866,-1.708461,0.0,973.61,443.784431,607.750,363.390762,-0.215252,-1.738553,1
3,0.0,381.37,85.030018,20.90,100.470845,0.713878,-1.138168,0.0,224.95,52.948258,...,-0.118586,-1.714493,0.0,844.47,380.029006,435.380,323.787033,-0.040911,-1.732718,1
4,0.0,222.75,34.748527,10.34,48.654118,1.381682,0.725784,0.0,304.70,74.047273,...,-0.146097,-1.799801,0.0,1007.16,453.126996,553.850,396.996852,-0.082355,-1.831018,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.0,374.66,95.925065,46.86,100.527604,0.382235,-1.479062,0.0,315.92,103.145264,...,-0.037527,-1.790909,0.0,1100.88,509.801104,616.000,424.279788,-0.133466,-1.768560,1
302,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.103204,-1.618407,0.0,1084.60,389.880555,460.460,361.132161,0.088210,-1.646804,0
303,0.0,385.00,79.063396,12.32,109.457156,1.067801,-0.484931,0.0,223.41,44.597271,...,0.044665,-1.670656,0.0,1025.42,447.274323,555.830,384.973968,-0.086593,-1.764833,1
304,0.0,416.24,67.661907,16.17,101.207492,1.366585,0.319284,0.0,202.40,37.707942,...,0.258779,-1.387479,0.0,1261.37,489.129581,590.645,433.093218,0.046193,-1.649547,1
305,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,-0.138565,-1.791682,0.0,1039.61,450.173481,563.970,399.206651,-0.036104,-1.800418,1

In [ ]:
trans_data_1=trans_data.loc[trans_data['Label']==1]
trans_data_0=trans_data.loc[trans_data['Label']==0]

In [ ]:
trans_data_1.to_csv('Gait_PD.csv',index=None)
trans_data_0.to_csv('Gait_HC.csv',index=None)