In [9]:
import pandas as pd
import numpy as np

In [10]:
merged_data=pd.read_csv("merged_data_some_visit.csv")

In [11]:
merged_data

,PATNO,"('NP1COG', 'BL')","('NP1COG', 'V02')","('NP1COG', 'V04')","('NP1COG', 'V06')","('NP1COG', 'V08')","('NP1COG', 'V10')","('NP1COG', 'V12')","('NP1HALL', 'BL')","('NP1HALL', 'V02')",...,"('SDMTOTAL', 'V08')","('SDMTOTAL', 'V10')","('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
0,3000,0.25,0.125,0.00,0.25,0.25,0.00,0.25,0.0,0.0,...,0.519608,0.500000,0.519608,1.000000,1.000000,0.933333,0.866667,0.933333,1.000000,HC
1,3001,0.00,0.000,0.25,0.00,0.00,0.00,0.25,0.0,0.0,...,0.470588,0.470588,0.441176,1.000000,0.800000,1.000000,0.866667,0.933333,1.000000,PD
2,3002,0.25,0.250,0.25,0.50,0.25,0.25,0.50,0.0,0.0,...,0.431373,0.421569,0.372549,0.866667,0.800000,0.866667,0.733333,1.000000,0.866667,PD
3,3003,0.00,0.000,0.00,0.00,0.00,0.00,0.25,0.0,0.0,...,0.480392,0.411765,0.421569,0.866667,0.866667,0.933333,0.866667,1.000000,0.800000,PD
4,3004,0.00,0.000,0.00,0.00,0.25,0.00,0.00,0.0,0.0,...,0.450980,0.519608,0.500000,0.866667,0.866667,1.000000,0.933333,1.000000,1.000000,HC
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
471,60059,0.25,0.250,0.00,0.00,0.00,0.00,0.00,0.0,0.0,...,0.156863,0.156863,0.156863,0.533333,0.533333,0.400000,0.733333,0.733333,0.533333,PRODROMA
472,60060,0.00,0.000,0.00,0.00,0.00,0.00,0.00,0.0,0.0,...,0.313725,0.254902,0.264706,0.800000,0.733333,0.733333,0.866667,0.866667,0.866667,PRODROMA
473,60063,0.00,0.000,0.00,0.00,0.00,0.25,0.25,0.0,0.0,...,0.156863,0.107843,0.117647,0.600000,0.600000,0.533333,0.533333,0.800000,0.400000,PRODROMA
474,65002,0.25,0.250,0.00,0.25,0.25,0.25,0.25,0.0,0.0,...,0.362745,0.421569,0.480392,0.800000,0.800000,0.733333,0.711111,0.688889,0.666667,GENUN
475,90456,0.25,0.250,0.25,0.50,0.25,0.25,0.25,0.0,0.0,...,0.215686,0.205882,0.215686,0.600000,0.533333,0.666667,0.466667,0.533333,0.466667,PRODROMA

In [12]:
new_df=merged_data.loc[merged_data['ENROLL_CAT']=='PD']

In [13]:
new_df2=merged_data.loc[merged_data['ENROLL_CAT']=='HC']

In [14]:
new_df.to_csv('PPMI_PD.csv',index=None)
new_df2.to_csv('PPMI_HC.csv',index=None)

In [6]:
frames = [new_df, new_df2]
result=pd.concat(frames)

In [7]:
result

,PATNO,"('NP1COG', 'BL')","('NP1COG', 'V01')","('NP1COG', 'V02')","('NP1COG', 'V03')","('NP1COG', 'V04')","('NP1COG', 'V05')","('NP1COG', 'V06')","('NP1COG', 'V07')","('NP1COG', 'V08')",...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
1,3001,0.00,0.00,0.00,0.00,0.25,0.00,0.0,0.00,0.00,...,0.441176,1.000000,0.933333,0.866667,0.800000,1.000000,0.866667,0.933333,1.000000,PD
2,3002,0.25,0.25,0.25,0.25,0.25,0.25,0.5,0.25,0.25,...,0.372549,0.866667,0.844444,0.822222,0.800000,0.866667,0.733333,1.000000,0.866667,PD
3,3003,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.25,0.00,...,0.421569,0.866667,0.866667,0.866667,0.866667,0.933333,0.866667,1.000000,0.800000,PD
6,3010,0.25,0.00,0.25,0.00,0.00,0.25,0.0,0.00,0.25,...,0.539216,0.666667,0.733333,0.800000,0.866667,0.866667,0.866667,0.800000,0.933333,PD
7,3027,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.372549,0.866667,0.800000,0.733333,0.666667,0.833333,1.000000,0.833333,0.666667,PD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
426,4090,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.421569,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.933333,0.933333,HC
434,4100,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.441176,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,HC
437,4104,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.382353,0.800000,0.822222,0.844444,0.866667,0.933333,0.666667,0.733333,0.866667,HC
447,4116,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.421569,0.866667,0.911111,0.955556,1.000000,0.733333,0.933333,0.733333,0.933333,HC
449,4118,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,...,0.372549,0.800000,0.777778,0.755556,0.733333,0.866667,0.800000,0.933333,0.733333,HC

In [8]:
result['ENROLL_CAT'] = result['ENROLL_CAT'].replace('HC',0)
result['ENROLL_CAT'] = result['ENROLL_CAT'].replace('PD',1)
result['ENROLL_CAT'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
trans_data=pd.read_csv('trans_data.csv')

In [16]:
trans_data

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,Total_Force_Left_skew,Total_Force_Left_kurt,Total_Force_Right_min,Total_Force_Right_max,Total_Force_Right_mean,Total_Force_Right_median,Total_Force_Right_std_dv,Total_Force_Right_skew,Total_Force_Right_kurt,Label
0,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,-0.021240,-1.813475,0.0,773.85,326.325488,455.510,288.823810,-0.061878,-1.788584,0
1,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,-0.019703,-1.774458,0.0,1129.26,469.552123,597.410,404.868046,-0.047013,-1.725542,1
2,0.0,295.13,60.031170,5.06,82.694408,1.058844,-0.369829,0.0,469.15,98.999946,...,0.030866,-1.708461,0.0,973.61,443.784431,607.750,363.390762,-0.215252,-1.738553,1
3,0.0,381.37,85.030018,20.90,100.470845,0.713878,-1.138168,0.0,224.95,52.948258,...,-0.118586,-1.714493,0.0,844.47,380.029006,435.380,323.787033,-0.040911,-1.732718,1
4,0.0,222.75,34.748527,10.34,48.654118,1.381682,0.725784,0.0,304.70,74.047273,...,-0.146097,-1.799801,0.0,1007.16,453.126996,553.850,396.996852,-0.082355,-1.831018,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,0.0,374.66,95.925065,46.86,100.527604,0.382235,-1.479062,0.0,315.92,103.145264,...,-0.037527,-1.790909,0.0,1100.88,509.801104,616.000,424.279788,-0.133466,-1.768560,1
302,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.103204,-1.618407,0.0,1084.60,389.880555,460.460,361.132161,0.088210,-1.646804,0
303,0.0,385.00,79.063396,12.32,109.457156,1.067801,-0.484931,0.0,223.41,44.597271,...,0.044665,-1.670656,0.0,1025.42,447.274323,555.830,384.973968,-0.086593,-1.764833,1
304,0.0,416.24,67.661907,16.17,101.207492,1.366585,0.319284,0.0,202.40,37.707942,...,0.258779,-1.387479,0.0,1261.37,489.129581,590.645,433.093218,0.046193,-1.649547,1
305,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,-0.138565,-1.791682,0.0,1039.61,450.173481,563.970,399.206651,-0.036104,-1.800418,1

In [17]:
trans_data_1=trans_data.loc[trans_data['Label']==1]
trans_data_0=trans_data.loc[trans_data['Label']==0]

In [18]:
trans_data_1.to_csv('Gait_PD.csv',index=None)
trans_data_0.to_csv('Gait_HC.csv',index=None)

In [13]:
all_hc=trans_data_0.merge(new_df2, how='cross')

In [14]:
all_hc['ENROLL_CAT']=all_hc['ENROLL_CAT'].replace('HC',0)
all_hc

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
0,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.519608,1.000000,1.000000,1.000000,1.000000,0.933333,0.866667,0.933333,1.000000,0
1,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.500000,0.866667,0.866667,0.866667,0.866667,1.000000,0.933333,1.000000,1.000000,0
2,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.343137,0.800000,0.800000,0.800000,0.800000,0.800000,0.600000,0.933333,0.666667,0
3,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.441176,0.733333,0.600000,0.466667,0.333333,0.866667,0.888889,0.911111,0.933333,0
4,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.323529,1.000000,0.977778,0.955556,0.933333,0.933333,0.733333,0.800000,0.733333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14163,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.421569,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.933333,0.933333,0
14164,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.441176,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0.933333,0
14165,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.382353,0.800000,0.822222,0.844444,0.866667,0.933333,0.666667,0.733333,0.866667,0
14166,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.421569,0.866667,0.911111,0.955556,1.000000,0.733333,0.933333,0.733333,0.933333,0
14167,0.0,481.03,85.801988,4.07,130.048673,1.278246,0.127049,0.0,325.27,59.328957,...,0.372549,0.800000,0.777778,0.755556,0.733333,0.866667,0.800000,0.933333,0.733333,0

In [15]:
all_pd=trans_data_1.merge(new_df, how='cross')
all_pd['ENROLL_CAT']=all_pd['ENROLL_CAT'].replace('PD',1)
all_pd

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
0,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,0.441176,1.000000,0.933333,0.866667,0.800000,1.000000,0.866667,0.933333,1.000000,1
1,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,0.372549,0.866667,0.844444,0.822222,0.800000,0.866667,0.733333,1.000000,0.866667,1
2,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,0.421569,0.866667,0.866667,0.866667,0.866667,0.933333,0.866667,1.000000,0.800000,1
3,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,0.539216,0.666667,0.733333,0.800000,0.866667,0.866667,0.866667,0.800000,0.933333,1
4,0.0,469.04,91.138454,10.34,140.755269,1.316082,0.095898,0.0,227.59,43.133334,...,0.372549,0.866667,0.800000,0.733333,0.666667,0.833333,1.000000,0.833333,0.666667,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62911,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.500000,0.933333,0.911111,0.888889,0.866667,0.733333,0.733333,0.733333,0.866667,1
62912,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.411765,0.933333,0.844444,0.755556,0.666667,0.866667,0.866667,0.600000,0.733333,1
62913,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.500000,1.000000,0.955556,0.911111,0.866667,1.000000,1.000000,1.000000,1.000000,1
62914,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.578431,0.733333,0.666667,0.600000,0.533333,0.800000,0.466667,0.733333,0.800000,1
62915,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.372549,1.000000,0.911111,0.822222,0.733333,0.800000,0.733333,0.666667,0.600000,1

In [16]:
frames = [all_hc, all_pd]
all_data=pd.concat(frames)

In [17]:
all_data

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
0,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.519608,1.000000,1.000000,1.000000,1.000000,0.933333,0.866667,0.933333,1.000000,0
1,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.500000,0.866667,0.866667,0.866667,0.866667,1.000000,0.933333,1.000000,1.000000,0
2,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.343137,0.800000,0.800000,0.800000,0.800000,0.800000,0.600000,0.933333,0.666667,0
3,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.441176,0.733333,0.600000,0.466667,0.333333,0.866667,0.888889,0.911111,0.933333,0
4,0.0,341.66,44.286986,0.00,80.152392,1.723044,1.565384,0.0,369.49,49.094092,...,0.323529,1.000000,0.977778,0.955556,0.933333,0.933333,0.733333,0.800000,0.733333,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62911,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.500000,0.933333,0.911111,0.888889,0.866667,0.733333,0.733333,0.733333,0.866667,1
62912,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.411765,0.933333,0.844444,0.755556,0.666667,0.866667,0.866667,0.600000,0.733333,1
62913,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.500000,1.000000,0.955556,0.911111,0.866667,1.000000,1.000000,1.000000,1.000000,1
62914,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.578431,0.733333,0.666667,0.600000,0.533333,0.800000,0.466667,0.733333,0.800000,1
62915,0.0,386.98,91.250953,26.84,113.421692,0.940093,-0.677070,0.0,198.55,46.039213,...,0.372549,1.000000,0.911111,0.822222,0.733333,0.800000,0.733333,0.666667,0.600000,1

In [18]:
all_data = all_data.sample(frac = 1)

In [19]:
all_data.to_csv('all_data.csv',index=None)

In [20]:
all_data

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
18146,0.0,214.61,37.020277,0.00,53.969608,1.236014,0.038325,0.0,149.27,25.506013,...,0.421569,0.866667,0.822222,0.777778,0.733333,0.866667,0.666667,0.866667,0.733333,1
10889,0.0,352.33,75.147229,15.18,110.080638,1.209468,-0.206666,0.0,239.91,50.002190,...,0.323529,1.000000,0.911111,0.822222,0.733333,1.000000,0.866667,1.000000,0.866667,1
39158,0.0,191.18,37.788152,0.00,51.915043,1.116222,-0.241190,0.0,232.54,49.425419,...,0.509804,0.800000,0.866667,0.933333,1.000000,0.866667,0.933333,1.000000,0.866667,1
9914,0.0,359.37,98.726611,22.77,118.990992,0.713494,-1.213054,0.0,221.32,54.925723,...,0.617647,0.600000,0.644444,0.688889,0.733333,0.733333,0.866667,0.733333,0.933333,0
53724,0.0,106.92,25.573761,17.71,27.669679,0.746620,-0.581370,0.0,225.83,60.707547,...,0.558824,0.933333,0.955556,0.977778,1.000000,0.866667,1.000000,0.666667,0.800000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16975,0.0,447.15,121.940410,12.32,146.812434,0.661143,-1.247997,0.0,349.25,83.354042,...,0.303922,0.666667,0.700000,0.733333,0.866667,1.000000,0.733333,1.000000,0.800000,1
8139,0.0,373.12,87.624953,6.82,111.563380,0.772101,-1.105776,0.0,304.48,80.239477,...,0.490196,0.933333,0.933333,0.933333,0.933333,1.000000,1.000000,1.000000,0.933333,0
56361,0.0,352.44,89.057512,20.90,106.927415,0.744929,-1.107776,0.0,188.76,41.320126,...,0.264706,0.933333,0.933333,0.933333,0.933333,0.866667,0.900000,0.933333,0.600000,1
2970,0.0,416.35,94.510985,10.23,127.782432,0.971296,-0.713021,0.0,300.85,71.632120,...,0.509804,1.000000,0.977778,0.955556,0.933333,1.000000,0.866667,1.000000,1.000000,0
50574,0.0,363.00,94.676716,20.90,117.320143,0.851085,-0.891779,0.0,197.78,47.804644,...,0.323529,0.866667,0.911111,0.955556,1.000000,1.000000,1.000000,0.933333,0.933333,1

In [21]:
p=all_data.drop(['Label'],axis=1)
p

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')",ENROLL_CAT
18146,0.0,214.61,37.020277,0.00,53.969608,1.236014,0.038325,0.0,149.27,25.506013,...,0.421569,0.866667,0.822222,0.777778,0.733333,0.866667,0.666667,0.866667,0.733333,1
10889,0.0,352.33,75.147229,15.18,110.080638,1.209468,-0.206666,0.0,239.91,50.002190,...,0.323529,1.000000,0.911111,0.822222,0.733333,1.000000,0.866667,1.000000,0.866667,1
39158,0.0,191.18,37.788152,0.00,51.915043,1.116222,-0.241190,0.0,232.54,49.425419,...,0.509804,0.800000,0.866667,0.933333,1.000000,0.866667,0.933333,1.000000,0.866667,1
9914,0.0,359.37,98.726611,22.77,118.990992,0.713494,-1.213054,0.0,221.32,54.925723,...,0.617647,0.600000,0.644444,0.688889,0.733333,0.733333,0.866667,0.733333,0.933333,0
53724,0.0,106.92,25.573761,17.71,27.669679,0.746620,-0.581370,0.0,225.83,60.707547,...,0.558824,0.933333,0.955556,0.977778,1.000000,0.866667,1.000000,0.666667,0.800000,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16975,0.0,447.15,121.940410,12.32,146.812434,0.661143,-1.247997,0.0,349.25,83.354042,...,0.303922,0.666667,0.700000,0.733333,0.866667,1.000000,0.733333,1.000000,0.800000,1
8139,0.0,373.12,87.624953,6.82,111.563380,0.772101,-1.105776,0.0,304.48,80.239477,...,0.490196,0.933333,0.933333,0.933333,0.933333,1.000000,1.000000,1.000000,0.933333,0
56361,0.0,352.44,89.057512,20.90,106.927415,0.744929,-1.107776,0.0,188.76,41.320126,...,0.264706,0.933333,0.933333,0.933333,0.933333,0.866667,0.900000,0.933333,0.600000,1
2970,0.0,416.35,94.510985,10.23,127.782432,0.971296,-0.713021,0.0,300.85,71.632120,...,0.509804,1.000000,0.977778,0.955556,0.933333,1.000000,0.866667,1.000000,1.000000,0
50574,0.0,363.00,94.676716,20.90,117.320143,0.851085,-0.891779,0.0,197.78,47.804644,...,0.323529,0.866667,0.911111,0.955556,1.000000,1.000000,1.000000,0.933333,0.933333,1

In [22]:
X=p.drop(['ENROLL_CAT'],axis=1)
X

,L1_min,L1_max,L1_mean,L1_median,L1_std_dv,L1_skew,L1_kurt,L2_min,L2_max,L2_mean,...,"('SDMTOTAL', 'V10')","('SDMTOTAL', 'V12')","('JLO_TOTRAW', 'BL')","('JLO_TOTRAW', 'V01')","('JLO_TOTRAW', 'V03')","('JLO_TOTRAW', 'V04')","('JLO_TOTRAW', 'V06')","('JLO_TOTRAW', 'V08')","('JLO_TOTRAW', 'V10')","('JLO_TOTRAW', 'V12')"
18146,0.0,214.61,37.020277,0.00,53.969608,1.236014,0.038325,0.0,149.27,25.506013,...,0.382353,0.421569,0.866667,0.822222,0.777778,0.733333,0.866667,0.666667,0.866667,0.733333
10889,0.0,352.33,75.147229,15.18,110.080638,1.209468,-0.206666,0.0,239.91,50.002190,...,0.333333,0.323529,1.000000,0.911111,0.822222,0.733333,1.000000,0.866667,1.000000,0.866667
39158,0.0,191.18,37.788152,0.00,51.915043,1.116222,-0.241190,0.0,232.54,49.425419,...,0.470588,0.509804,0.800000,0.866667,0.933333,1.000000,0.866667,0.933333,1.000000,0.866667
9914,0.0,359.37,98.726611,22.77,118.990992,0.713494,-1.213054,0.0,221.32,54.925723,...,0.588235,0.617647,0.600000,0.644444,0.688889,0.733333,0.733333,0.866667,0.733333,0.933333
53724,0.0,106.92,25.573761,17.71,27.669679,0.746620,-0.581370,0.0,225.83,60.707547,...,0.519608,0.558824,0.933333,0.955556,0.977778,1.000000,0.866667,1.000000,0.666667,0.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16975,0.0,447.15,121.940410,12.32,146.812434,0.661143,-1.247997,0.0,349.25,83.354042,...,0.392157,0.303922,0.666667,0.700000,0.733333,0.866667,1.000000,0.733333,1.000000,0.800000
8139,0.0,373.12,87.624953,6.82,111.563380,0.772101,-1.105776,0.0,304.48,80.239477,...,0.500000,0.490196,0.933333,0.933333,0.933333,0.933333,1.000000,1.000000,1.000000,0.933333
56361,0.0,352.44,89.057512,20.90,106.927415,0.744929,-1.107776,0.0,188.76,41.320126,...,0.225490,0.264706,0.933333,0.933333,0.933333,0.933333,0.866667,0.900000,0.933333,0.600000
2970,0.0,416.35,94.510985,10.23,127.782432,0.971296,-0.713021,0.0,300.85,71.632120,...,0.500000,0.509804,1.000000,0.977778,0.955556,0.933333,1.000000,0.866667,1.000000,1.000000
50574,0.0,363.00,94.676716,20.90,117.320143,0.851085,-0.891779,0.0,197.78,47.804644,...,0.372549,0.323529,0.866667,0.911111,0.955556,1.000000,1.000000,1.000000,0.933333,0.933333

In [23]:
y=p['ENROLL_CAT'].values
# y.value_counts()

In [24]:
from sklearn import decomposition
import os
import scipy.stats as sc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier

In [82]:
score_val = 0
min_range = 0
max_range = 10
state = 0
neigh = 0

for rand_state in range(min_range, max_range):
    X_train, X_test, y_train1, y_test1 = train_test_split(X, y, random_state = rand_state)
    y_train = pd.DataFrame(y_train1)
    y_test = pd.DataFrame(y_test1)

    scaler = MinMaxScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    
    for neighbors in ([1, 3, 5, 10, 15, 20]):
        knn = KNeighborsClassifier(n_neighbors = neighbors)
        knn.fit(X_train, np.ravel(y_train,order='C'))
        score = knn.score(X_test, np.ravel(y_test))

        if score > score_val:
            neigh = neighbors
            score_val = score
            state = rand_state

    print('{} out of {} done'.format(rand_state - min_range, max_range - min_range))
print("Neighbors = {}, Score = {}, Random State = {}".format(neigh, score_val, state))

0 out of 10 done
1 out of 10 done
2 out of 10 done
3 out of 10 done
4 out of 10 done
5 out of 10 done
6 out of 10 done
7 out of 10 done
8 out of 10 done
9 out of 10 done
Neighbors = 1, Score = 1.0, Random State = 0

In [83]:
X=trans_data.drop(['Label'],axis=1)
y=trans_data['Label'].values

In [85]:
score_val = 0
min_range = 0
max_range = 1000
state = 0
neigh = 0

for rand_state in range(min_range, max_range):
    X_train, X_test, y_train1, y_test1 = train_test_split(X, y, random_state = rand_state)
    y_train = pd.DataFrame(y_train1)
    y_test = pd.DataFrame(y_test1)

    scaler = MinMaxScaler().fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    
    
    for neighbors in ([1, 3, 5, 10, 15, 20]):
        knn = KNeighborsClassifier(n_neighbors = neighbors)
        knn.fit(X_train, np.ravel(y_train,order='C'))
        score = knn.score(X_test, np.ravel(y_test))

        if score > score_val:
            neigh = neighbors
            score_val = score
            state = rand_state

    print('{} out of {} done'.format(rand_state - min_range, max_range - min_range))
print("Neighbors = {}, Score = {}, Random State = {}".format(neigh, score_val, state))

0 out of 1000 done
1 out of 1000 done
2 out of 1000 done
3 out of 1000 done
4 out of 1000 done
5 out of 1000 done
6 out of 1000 done
7 out of 1000 done
8 out of 1000 done
9 out of 1000 done
10 out of 1000 done
11 out of 1000 done
12 out of 1000 done
13 out of 1000 done
14 out of 1000 done
15 out of 1000 done
16 out of 1000 done
17 out of 1000 done
18 out of 1000 done
19 out of 1000 done
20 out of 1000 done
21 out of 1000 done
22 out of 1000 done
23 out of 1000 done
24 out of 1000 done
25 out of 1000 done
26 out of 1000 done
27 out of 1000 done
28 out of 1000 done
29 out of 1000 done
30 out of 1000 done
31 out of 1000 done
32 out of 1000 done
33 out of 1000 done
34 out of 1000 done
35 out of 1000 done
36 out of 1000 done
37 out of 1000 done
38 out of 1000 done
39 out of 1000 done
40 out of 1000 done
41 out of 1000 done
42 out of 1000 done
43 out of 1000 done
44 out of 1000 done
45 out of 1000 done
46 out of 1000 done
47 out of 1000 done
48 out of 1000 done
49 out of 1000 done
50 out of 1000 done
51 out of 1000 done
52 out of 1000 done
53 out of 1000 done
54 out of 1000 done
55 out of 1000 done
56 out of 1000 done
57 out of 1000 done
58 out of 1000 done
59 out of 1000 done
60 out of 1000 done
61 out of 1000 done
62 out of 1000 done
63 out of 1000 done
64 out of 1000 done
65 out of 1000 done
66 out of 1000 done
67 out of 1000 done
68 out of 1000 done
69 out of 1000 done
70 out of 1000 done
71 out of 1000 done
72 out of 1000 done
73 out of 1000 done
74 out of 1000 done
75 out of 1000 done
76 out of 1000 done
77 out of 1000 done
78 out of 1000 done
79 out of 1000 done
80 out of 1000 done
81 out of 1000 done
82 out of 1000 done
83 out of 1000 done
84 out of 1000 done
85 out of 1000 done
86 out of 1000 done
87 out of 1000 done
88 out of 1000 done
89 out of 1000 done
90 out of 1000 done
91 out of 1000 done
92 out of 1000 done
93 out of 1000 done
94 out of 1000 done
95 out of 1000 done
96 out of 1000 done
97 out of 1000 done
98 out of 1000 done
99 out of 1000 done
100 out of 1000 done
101 out of 1000 done
102 out of 1000 done
103 out of 1000 done
104 out of 1000 done
105 out of 1000 done
106 out of 1000 done
107 out of 1000 done
108 out of 1000 done
109 out of 1000 done
110 out of 1000 done
111 out of 1000 done
112 out of 1000 done
113 out of 1000 done
114 out of 1000 done
115 out of 1000 done
116 out of 1000 done
117 out of 1000 done
118 out of 1000 done
119 out of 1000 done
120 out of 1000 done
121 out of 1000 done
122 out of 1000 done
123 out of 1000 done
124 out of 1000 done
125 out of 1000 done
126 out of 1000 done
127 out of 1000 done
128 out of 1000 done
129 out of 1000 done
130 out of 1000 done
131 out of 1000 done
132 out of 1000 done
133 out of 1000 done
134 out of 1000 done
135 out of 1000 done
136 out of 1000 done
137 out of 1000 done
138 out of 1000 done
139 out of 1000 done
140 out of 1000 done
141 out of 1000 done
142 out of 1000 done
143 out of 1000 done
144 out of 1000 done
145 out of 1000 done
146 out of 1000 done
147 out of 1000 done
148 out of 1000 done
149 out of 1000 done
150 out of 1000 done
151 out of 1000 done
152 out of 1000 done
153 out of 1000 done
154 out of 1000 done
155 out of 1000 done
156 out of 1000 done
157 out of 1000 done
158 out of 1000 done
159 out of 1000 done
160 out of 1000 done
161 out of 1000 done
162 out of 1000 done
163 out of 1000 done
164 out of 1000 done
165 out of 1000 done
166 out of 1000 done
167 out of 1000 done
168 out of 1000 done
169 out of 1000 done
170 out of 1000 done
171 out of 1000 done
172 out of 1000 done
173 out of 1000 done
174 out of 1000 done
175 out of 1000 done
176 out of 1000 done
177 out of 1000 done
178 out of 1000 done
179 out of 1000 done
180 out of 1000 done
181 out of 1000 done
182 out of 1000 done
183 out of 1000 done
184 out of 1000 done
185 out of 1000 done
186 out of 1000 done
187 out of 1000 done
188 out of 1000 done
189 out of 1000 done
190 out of 1000 done
191 out of 1000 done
192 out of 1000 done
193 out of 1000 done
194 out of 1000 done
195 out of 1000 done
196 out of 1000 done
197 out of 1000 done
198 out of 1000 done
199 out of 1000 done
200 out of 1000 done
201 out of 1000 done
202 out of 1000 done
203 out of 1000 done
204 out of 1000 done
205 out of 1000 done
206 out of 1000 done
207 out of 1000 done
208 out of 1000 done
209 out of 1000 done
210 out of 1000 done
211 out of 1000 done
212 out of 1000 done
213 out of 1000 done
214 out of 1000 done
215 out of 1000 done
216 out of 1000 done
217 out of 1000 done
218 out of 1000 done
219 out of 1000 done
220 out of 1000 done
221 out of 1000 done
222 out of 1000 done
223 out of 1000 done
224 out of 1000 done
225 out of 1000 done
226 out of 1000 done
227 out of 1000 done
228 out of 1000 done
229 out of 1000 done
230 out of 1000 done
231 out of 1000 done
232 out of 1000 done
233 out of 1000 done
234 out of 1000 done
235 out of 1000 done
236 out of 1000 done
237 out of 1000 done
238 out of 1000 done
239 out of 1000 done
240 out of 1000 done
241 out of 1000 done
242 out of 1000 done
243 out of 1000 done
244 out of 1000 done
245 out of 1000 done
246 out of 1000 done
247 out of 1000 done
248 out of 1000 done
249 out of 1000 done
250 out of 1000 done
251 out of 1000 done
252 out of 1000 done
253 out of 1000 done
254 out of 1000 done
255 out of 1000 done
256 out of 1000 done
257 out of 1000 done
258 out of 1000 done
259 out of 1000 done
260 out of 1000 done
261 out of 1000 done
262 out of 1000 done
263 out of 1000 done
264 out of 1000 done
265 out of 1000 done
266 out of 1000 done
267 out of 1000 done
268 out of 1000 done
269 out of 1000 done
270 out of 1000 done
271 out of 1000 done
272 out of 1000 done
273 out of 1000 done
274 out of 1000 done
275 out of 1000 done
276 out of 1000 done
277 out of 1000 done
278 out of 1000 done
279 out of 1000 done
280 out of 1000 done
281 out of 1000 done
282 out of 1000 done
283 out of 1000 done
284 out of 1000 done
285 out of 1000 done
286 out of 1000 done
287 out of 1000 done
288 out of 1000 done
289 out of 1000 done
290 out of 1000 done
291 out of 1000 done
292 out of 1000 done
293 out of 1000 done
294 out of 1000 done
295 out of 1000 done
296 out of 1000 done
297 out of 1000 done
298 out of 1000 done
299 out of 1000 done
300 out of 1000 done
301 out of 1000 done
302 out of 1000 done
303 out of 1000 done
304 out of 1000 done
305 out of 1000 done
306 out of 1000 done
307 out of 1000 done
308 out of 1000 done
309 out of 1000 done
310 out of 1000 done
311 out of 1000 done
312 out of 1000 done
313 out of 1000 done
314 out of 1000 done
315 out of 1000 done
316 out of 1000 done
317 out of 1000 done
318 out of 1000 done
319 out of 1000 done
320 out of 1000 done
321 out of 1000 done
322 out of 1000 done
323 out of 1000 done
324 out of 1000 done
325 out of 1000 done
326 out of 1000 done
327 out of 1000 done
328 out of 1000 done
329 out of 1000 done
330 out of 1000 done
331 out of 1000 done
332 out of 1000 done
333 out of 1000 done
334 out of 1000 done
335 out of 1000 done
336 out of 1000 done
337 out of 1000 done
338 out of 1000 done
339 out of 1000 done
340 out of 1000 done
341 out of 1000 done
342 out of 1000 done
343 out of 1000 done
344 out of 1000 done
345 out of 1000 done
346 out of 1000 done
347 out of 1000 done
348 out of 1000 done
349 out of 1000 done
350 out of 1000 done
351 out of 1000 done
352 out of 1000 done
353 out of 1000 done
354 out of 1000 done
355 out of 1000 done
356 out of 1000 done
357 out of 1000 done
358 out of 1000 done
359 out of 1000 done
360 out of 1000 done
361 out of 1000 done
362 out of 1000 done
363 out of 1000 done
364 out of 1000 done
365 out of 1000 done
366 out of 1000 done
367 out of 1000 done
368 out of 1000 done
369 out of 1000 done
370 out of 1000 done
371 out of 1000 done
372 out of 1000 done
373 out of 1000 done
374 out of 1000 done
375 out of 1000 done
376 out of 1000 done
377 out of 1000 done
378 out of 1000 done
379 out of 1000 done
380 out of 1000 done
381 out of 1000 done
382 out of 1000 done
383 out of 1000 done
384 out of 1000 done
385 out of 1000 done
386 out of 1000 done
387 out of 1000 done
388 out of 1000 done
389 out of 1000 done
390 out of 1000 done
391 out of 1000 done
392 out of 1000 done
393 out of 1000 done
394 out of 1000 done
395 out of 1000 done

396 out of 1000 done
397 out of 1000 done
398 out of 1000 done
399 out of 1000 done
400 out of 1000 done
401 out of 1000 done
402 out of 1000 done
403 out of 1000 done
404 out of 1000 done
405 out of 1000 done
406 out of 1000 done
407 out of 1000 done
408 out of 1000 done
409 out of 1000 done
410 out of 1000 done
411 out of 1000 done
412 out of 1000 done
413 out of 1000 done
414 out of 1000 done
415 out of 1000 done
416 out of 1000 done
417 out of 1000 done
418 out of 1000 done
419 out of 1000 done
420 out of 1000 done
421 out of 1000 done
422 out of 1000 done
423 out of 1000 done
424 out of 1000 done
425 out of 1000 done
426 out of 1000 done
427 out of 1000 done
428 out of 1000 done
429 out of 1000 done
430 out of 1000 done
431 out of 1000 done
432 out of 1000 done
433 out of 1000 done
434 out of 1000 done
435 out of 1000 done
436 out of 1000 done
437 out of 1000 done
438 out of 1000 done
439 out of 1000 done
440 out of 1000 done
441 out of 1000 done
442 out of 1000 done
443 out of 1000 done
444 out of 1000 done
445 out of 1000 done
446 out of 1000 done
447 out of 1000 done
448 out of 1000 done
449 out of 1000 done
450 out of 1000 done
451 out of 1000 done
452 out of 1000 done
453 out of 1000 done
454 out of 1000 done
455 out of 1000 done
456 out of 1000 done
457 out of 1000 done
458 out of 1000 done
459 out of 1000 done
460 out of 1000 done
461 out of 1000 done
462 out of 1000 done
463 out of 1000 done
464 out of 1000 done
465 out of 1000 done
466 out of 1000 done
467 out of 1000 done
468 out of 1000 done
469 out of 1000 done
470 out of 1000 done
471 out of 1000 done
472 out of 1000 done
473 out of 1000 done
474 out of 1000 done
475 out of 1000 done
476 out of 1000 done
477 out of 1000 done
478 out of 1000 done
479 out of 1000 done
480 out of 1000 done
481 out of 1000 done
482 out of 1000 done
483 out of 1000 done
484 out of 1000 done
485 out of 1000 done
486 out of 1000 done
487 out of 1000 done
488 out of 1000 done
489 out of 1000 done
490 out of 1000 done
491 out of 1000 done
492 out of 1000 done
493 out of 1000 done
494 out of 1000 done
495 out of 1000 done
496 out of 1000 done
497 out of 1000 done
498 out of 1000 done
499 out of 1000 done
500 out of 1000 done
501 out of 1000 done
502 out of 1000 done
503 out of 1000 done
504 out of 1000 done
505 out of 1000 done
506 out of 1000 done
507 out of 1000 done
508 out of 1000 done
509 out of 1000 done
510 out of 1000 done
511 out of 1000 done
512 out of 1000 done
513 out of 1000 done
514 out of 1000 done
515 out of 1000 done
516 out of 1000 done
517 out of 1000 done
518 out of 1000 done
519 out of 1000 done
520 out of 1000 done
521 out of 1000 done
522 out of 1000 done
523 out of 1000 done
524 out of 1000 done
525 out of 1000 done
526 out of 1000 done
527 out of 1000 done
528 out of 1000 done
529 out of 1000 done
530 out of 1000 done
531 out of 1000 done
532 out of 1000 done
533 out of 1000 done
534 out of 1000 done
535 out of 1000 done
536 out of 1000 done
537 out of 1000 done
538 out of 1000 done
539 out of 1000 done
540 out of 1000 done
541 out of 1000 done
542 out of 1000 done
543 out of 1000 done
544 out of 1000 done
545 out of 1000 done
546 out of 1000 done
547 out of 1000 done
548 out of 1000 done
549 out of 1000 done
550 out of 1000 done
551 out of 1000 done
552 out of 1000 done
553 out of 1000 done
554 out of 1000 done
555 out of 1000 done
556 out of 1000 done
557 out of 1000 done
558 out of 1000 done
559 out of 1000 done
560 out of 1000 done
561 out of 1000 done
562 out of 1000 done
563 out of 1000 done
564 out of 1000 done
565 out of 1000 done
566 out of 1000 done
567 out of 1000 done
568 out of 1000 done
569 out of 1000 done
570 out of 1000 done
571 out of 1000 done
572 out of 1000 done
573 out of 1000 done
574 out of 1000 done
575 out of 1000 done
576 out of 1000 done
577 out of 1000 done
578 out of 1000 done
579 out of 1000 done
580 out of 1000 done
581 out of 1000 done
582 out of 1000 done
583 out of 1000 done
584 out of 1000 done
585 out of 1000 done
586 out of 1000 done
587 out of 1000 done
588 out of 1000 done
589 out of 1000 done
590 out of 1000 done
591 out of 1000 done
592 out of 1000 done
593 out of 1000 done
594 out of 1000 done
595 out of 1000 done
596 out of 1000 done
597 out of 1000 done
598 out of 1000 done
599 out of 1000 done
600 out of 1000 done
601 out of 1000 done
602 out of 1000 done
603 out of 1000 done
604 out of 1000 done
605 out of 1000 done
606 out of 1000 done
607 out of 1000 done
608 out of 1000 done
609 out of 1000 done
610 out of 1000 done
611 out of 1000 done
612 out of 1000 done
613 out of 1000 done
614 out of 1000 done
615 out of 1000 done
616 out of 1000 done
617 out of 1000 done
618 out of 1000 done
619 out of 1000 done
620 out of 1000 done
621 out of 1000 done
622 out of 1000 done
623 out of 1000 done
624 out of 1000 done
625 out of 1000 done
626 out of 1000 done
627 out of 1000 done
628 out of 1000 done
629 out of 1000 done
630 out of 1000 done
631 out of 1000 done
632 out of 1000 done
633 out of 1000 done
634 out of 1000 done
635 out of 1000 done
636 out of 1000 done
637 out of 1000 done
638 out of 1000 done
639 out of 1000 done
640 out of 1000 done
641 out of 1000 done
642 out of 1000 done
643 out of 1000 done
644 out of 1000 done
645 out of 1000 done
646 out of 1000 done
647 out of 1000 done
648 out of 1000 done
649 out of 1000 done
650 out of 1000 done
651 out of 1000 done
652 out of 1000 done
653 out of 1000 done
654 out of 1000 done
655 out of 1000 done
656 out of 1000 done
657 out of 1000 done
658 out of 1000 done
659 out of 1000 done
660 out of 1000 done
661 out of 1000 done
662 out of 1000 done
663 out of 1000 done
664 out of 1000 done
665 out of 1000 done
666 out of 1000 done
667 out of 1000 done
668 out of 1000 done
669 out of 1000 done
670 out of 1000 done
671 out of 1000 done
672 out of 1000 done
673 out of 1000 done
674 out of 1000 done
675 out of 1000 done
676 out of 1000 done
677 out of 1000 done
678 out of 1000 done
679 out of 1000 done
680 out of 1000 done
681 out of 1000 done
682 out of 1000 done
683 out of 1000 done
684 out of 1000 done
685 out of 1000 done
686 out of 1000 done
687 out of 1000 done
688 out of 1000 done
689 out of 1000 done
690 out of 1000 done
691 out of 1000 done
692 out of 1000 done
693 out of 1000 done
694 out of 1000 done
695 out of 1000 done
696 out of 1000 done
697 out of 1000 done
698 out of 1000 done
699 out of 1000 done
700 out of 1000 done
701 out of 1000 done
702 out of 1000 done
703 out of 1000 done
704 out of 1000 done
705 out of 1000 done
706 out of 1000 done
707 out of 1000 done
708 out of 1000 done
709 out of 1000 done
710 out of 1000 done
711 out of 1000 done
712 out of 1000 done
713 out of 1000 done
714 out of 1000 done
715 out of 1000 done
716 out of 1000 done
717 out of 1000 done
718 out of 1000 done
719 out of 1000 done
720 out of 1000 done
721 out of 1000 done
722 out of 1000 done
723 out of 1000 done
724 out of 1000 done
725 out of 1000 done
726 out of 1000 done
727 out of 1000 done
728 out of 1000 done
729 out of 1000 done
730 out of 1000 done
731 out of 1000 done
732 out of 1000 done
733 out of 1000 done
734 out of 1000 done
735 out of 1000 done
736 out of 1000 done
737 out of 1000 done
738 out of 1000 done
739 out of 1000 done
740 out of 1000 done
741 out of 1000 done
742 out of 1000 done
743 out of 1000 done
744 out of 1000 done
745 out of 1000 done
746 out of 1000 done
747 out of 1000 done
748 out of 1000 done
749 out of 1000 done
750 out of 1000 done
751 out of 1000 done
752 out of 1000 done
753 out of 1000 done
754 out of 1000 done
755 out of 1000 done
756 out of 1000 done
757 out of 1000 done
758 out of 1000 done
759 out of 1000 done
760 out of 1000 done
761 out of 1000 done
762 out of 1000 done
763 out of 1000 done
764 out of 1000 done
765 out of 1000 done
766 out of 1000 done
767 out of 1000 done
768 out of 1000 done
769 out of 1000 done
770 out of 1000 done
771 out of 1000 done
772 out of 1000 done
773 out of 1000 done
774 out of 1000 done
775 out of 1000 done
776 out of 1000 done
777 out of 1000 done
778 out of 1000 done
779 out of 1000 done
780 out of 1000 done
781 out of 1000 done
782 out of 1000 done
783 out of 1000 done
784 out of 1000 done
785 out of 1000 done
786 out of 1000 done

787 out of 1000 done
788 out of 1000 done
789 out of 1000 done
790 out of 1000 done
791 out of 1000 done
792 out of 1000 done
793 out of 1000 done
794 out of 1000 done
795 out of 1000 done
796 out of 1000 done
797 out of 1000 done
798 out of 1000 done
799 out of 1000 done
800 out of 1000 done
801 out of 1000 done
802 out of 1000 done
803 out of 1000 done
804 out of 1000 done
805 out of 1000 done
806 out of 1000 done
807 out of 1000 done
808 out of 1000 done
809 out of 1000 done
810 out of 1000 done
811 out of 1000 done
812 out of 1000 done
813 out of 1000 done
814 out of 1000 done
815 out of 1000 done
816 out of 1000 done
817 out of 1000 done
818 out of 1000 done
819 out of 1000 done
820 out of 1000 done
821 out of 1000 done
822 out of 1000 done
823 out of 1000 done
824 out of 1000 done
825 out of 1000 done
826 out of 1000 done
827 out of 1000 done
828 out of 1000 done
829 out of 1000 done
830 out of 1000 done
831 out of 1000 done
832 out of 1000 done
833 out of 1000 done
834 out of 1000 done
835 out of 1000 done
836 out of 1000 done
837 out of 1000 done
838 out of 1000 done
839 out of 1000 done
840 out of 1000 done
841 out of 1000 done
842 out of 1000 done
843 out of 1000 done
844 out of 1000 done
845 out of 1000 done
846 out of 1000 done
847 out of 1000 done
848 out of 1000 done
849 out of 1000 done
850 out of 1000 done
851 out of 1000 done
852 out of 1000 done
853 out of 1000 done
854 out of 1000 done
855 out of 1000 done
856 out of 1000 done
857 out of 1000 done
858 out of 1000 done
859 out of 1000 done
860 out of 1000 done
861 out of 1000 done
862 out of 1000 done
863 out of 1000 done
864 out of 1000 done
865 out of 1000 done
866 out of 1000 done
867 out of 1000 done
868 out of 1000 done
869 out of 1000 done
870 out of 1000 done
871 out of 1000 done
872 out of 1000 done
873 out of 1000 done
874 out of 1000 done
875 out of 1000 done
876 out of 1000 done
877 out of 1000 done
878 out of 1000 done
879 out of 1000 done
880 out of 1000 done
881 out of 1000 done
882 out of 1000 done
883 out of 1000 done
884 out of 1000 done
885 out of 1000 done
886 out of 1000 done
887 out of 1000 done
888 out of 1000 done
889 out of 1000 done
890 out of 1000 done
891 out of 1000 done
892 out of 1000 done
893 out of 1000 done
894 out of 1000 done
895 out of 1000 done
896 out of 1000 done
897 out of 1000 done
898 out of 1000 done
899 out of 1000 done
900 out of 1000 done
901 out of 1000 done
902 out of 1000 done
903 out of 1000 done
904 out of 1000 done
905 out of 1000 done
906 out of 1000 done
907 out of 1000 done
908 out of 1000 done
909 out of 1000 done
910 out of 1000 done
911 out of 1000 done
912 out of 1000 done
913 out of 1000 done
914 out of 1000 done
915 out of 1000 done
916 out of 1000 done
917 out of 1000 done
918 out of 1000 done
919 out of 1000 done
920 out of 1000 done
921 out of 1000 done
922 out of 1000 done
923 out of 1000 done
924 out of 1000 done
925 out of 1000 done
926 out of 1000 done
927 out of 1000 done
928 out of 1000 done
929 out of 1000 done
930 out of 1000 done
931 out of 1000 done
932 out of 1000 done
933 out of 1000 done
934 out of 1000 done
935 out of 1000 done
936 out of 1000 done
937 out of 1000 done
938 out of 1000 done
939 out of 1000 done
940 out of 1000 done
941 out of 1000 done
942 out of 1000 done
943 out of 1000 done
944 out of 1000 done
945 out of 1000 done
946 out of 1000 done
947 out of 1000 done
948 out of 1000 done
949 out of 1000 done
950 out of 1000 done
951 out of 1000 done
952 out of 1000 done
953 out of 1000 done
954 out of 1000 done
955 out of 1000 done
956 out of 1000 done
957 out of 1000 done
958 out of 1000 done
959 out of 1000 done
960 out of 1000 done
961 out of 1000 done
962 out of 1000 done
963 out of 1000 done
964 out of 1000 done
965 out of 1000 done
966 out of 1000 done
967 out of 1000 done
968 out of 1000 done
969 out of 1000 done
970 out of 1000 done
971 out of 1000 done
972 out of 1000 done
973 out of 1000 done
974 out of 1000 done
975 out of 1000 done
976 out of 1000 done
977 out of 1000 done
978 out of 1000 done
979 out of 1000 done
980 out of 1000 done
981 out of 1000 done
982 out of 1000 done
983 out of 1000 done
984 out of 1000 done
985 out of 1000 done
986 out of 1000 done
987 out of 1000 done
988 out of 1000 done
989 out of 1000 done
990 out of 1000 done
991 out of 1000 done
992 out of 1000 done
993 out of 1000 done
994 out of 1000 done
995 out of 1000 done
996 out of 1000 done
997 out of 1000 done
998 out of 1000 done
999 out of 1000 done
Neighbors = 1, Score = 0.987012987012987, Random State = 598